version: '3.8'

services:
  web:
    image: php:apache
    container_name: apache-server
    volumes:
      - ./apache-php:/var/www/html  # Make sure this path matches the default Apache directory
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
