# Use the official Apache image as the base image
FROM httpd:latest

# Copy the contents of the 'my-website' folder to Apache's document root
COPY index.html /usr/local/apache2/htdocs/

# Expose the default Apache port (80)
EXPOSE 80